server:
  port: 8080

spring:
  application:
    name: gateway

  profiles:
    active: native, gateway

  config:
    import: optional:configserver:http://localhost:8888

eureka:
  password: password
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

