spring:
  application:
    name: address-service

  profiles:
    active: native, mysql

  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8081
  servlet:
    context-path: /address-service

eureka:
  password: password
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
